/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PostAuthRouteImport } from './routes/post-auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as AuthenticatedTimeCalendarRouteImport } from './routes/_authenticated/time-calendar'
import { Route as AuthenticatedSopLibraryRouteImport } from './routes/_authenticated/sop-library'
import { Route as AuthenticatedSightlineRouteImport } from './routes/_authenticated/sightline'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedKnowledgeBaseRouteImport } from './routes/_authenticated/knowledge-base'
import { Route as AuthenticatedGrowthRoadmapRouteImport } from './routes/_authenticated/growth-roadmap'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSopLibraryNewRouteImport } from './routes/_authenticated/sop-library.new'
import { Route as AuthenticatedSopLibraryIdRouteImport } from './routes/_authenticated/sop-library.$id'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedDashboardScenariosRouteImport } from './routes/_authenticated/dashboard.scenarios'
import { Route as AuthenticatedDashboardRateRouteImport } from './routes/_authenticated/dashboard.rate'
import { Route as AuthenticatedDashboardKnowledgeRouteImport } from './routes/_authenticated/dashboard.knowledge'
import { Route as AuthenticatedDashboardHealthRouteImport } from './routes/_authenticated/dashboard.health'
import { Route as AuthenticatedDashboardGrowthRouteImport } from './routes/_authenticated/dashboard.growth'
import { Route as AuthenticatedDashboardBvaRouteImport } from './routes/_authenticated/dashboard.bva'
import { Route as AuthenticatedDashboardAnnualSummaryRouteImport } from './routes/_authenticated/dashboard.annual-summary'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PostAuthRoute = PostAuthRouteImport.update({
  id: '/post-auth',
  path: '/post-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTimeCalendarRoute =
  AuthenticatedTimeCalendarRouteImport.update({
    id: '/time-calendar',
    path: '/time-calendar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSopLibraryRoute = AuthenticatedSopLibraryRouteImport.update({
  id: '/sop-library',
  path: '/sop-library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSightlineRoute = AuthenticatedSightlineRouteImport.update({
  id: '/sightline',
  path: '/sightline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKnowledgeBaseRoute =
  AuthenticatedKnowledgeBaseRouteImport.update({
    id: '/knowledge-base',
    path: '/knowledge-base',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGrowthRoadmapRoute =
  AuthenticatedGrowthRoadmapRouteImport.update({
    id: '/growth-roadmap',
    path: '/growth-roadmap',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSopLibraryNewRoute =
  AuthenticatedSopLibraryNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSopLibraryRoute,
  } as any)
const AuthenticatedSopLibraryIdRoute =
  AuthenticatedSopLibraryIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedSopLibraryRoute,
  } as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProjectsRoute,
} as any)
const AuthenticatedDashboardScenariosRoute =
  AuthenticatedDashboardScenariosRouteImport.update({
    id: '/scenarios',
    path: '/scenarios',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardRateRoute =
  AuthenticatedDashboardRateRouteImport.update({
    id: '/rate',
    path: '/rate',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardKnowledgeRoute =
  AuthenticatedDashboardKnowledgeRouteImport.update({
    id: '/knowledge',
    path: '/knowledge',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardHealthRoute =
  AuthenticatedDashboardHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardGrowthRoute =
  AuthenticatedDashboardGrowthRouteImport.update({
    id: '/growth',
    path: '/growth',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBvaRoute =
  AuthenticatedDashboardBvaRouteImport.update({
    id: '/bva',
    path: '/bva',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAnnualSummaryRoute =
  AuthenticatedDashboardAnnualSummaryRouteImport.update({
    id: '/annual-summary',
    path: '/annual-summary',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/post-auth': typeof PostAuthRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/growth-roadmap': typeof AuthenticatedGrowthRoadmapRoute
  '/knowledge-base': typeof AuthenticatedKnowledgeBaseRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/sightline': typeof AuthenticatedSightlineRoute
  '/sop-library': typeof AuthenticatedSopLibraryRouteWithChildren
  '/time-calendar': typeof AuthenticatedTimeCalendarRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/dashboard/annual-summary': typeof AuthenticatedDashboardAnnualSummaryRoute
  '/dashboard/bva': typeof AuthenticatedDashboardBvaRoute
  '/dashboard/growth': typeof AuthenticatedDashboardGrowthRoute
  '/dashboard/health': typeof AuthenticatedDashboardHealthRoute
  '/dashboard/knowledge': typeof AuthenticatedDashboardKnowledgeRoute
  '/dashboard/rate': typeof AuthenticatedDashboardRateRoute
  '/dashboard/scenarios': typeof AuthenticatedDashboardScenariosRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/sop-library/$id': typeof AuthenticatedSopLibraryIdRoute
  '/sop-library/new': typeof AuthenticatedSopLibraryNewRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/post-auth': typeof PostAuthRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/growth-roadmap': typeof AuthenticatedGrowthRoadmapRoute
  '/knowledge-base': typeof AuthenticatedKnowledgeBaseRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/sightline': typeof AuthenticatedSightlineRoute
  '/sop-library': typeof AuthenticatedSopLibraryRouteWithChildren
  '/time-calendar': typeof AuthenticatedTimeCalendarRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/dashboard/annual-summary': typeof AuthenticatedDashboardAnnualSummaryRoute
  '/dashboard/bva': typeof AuthenticatedDashboardBvaRoute
  '/dashboard/growth': typeof AuthenticatedDashboardGrowthRoute
  '/dashboard/health': typeof AuthenticatedDashboardHealthRoute
  '/dashboard/knowledge': typeof AuthenticatedDashboardKnowledgeRoute
  '/dashboard/rate': typeof AuthenticatedDashboardRateRoute
  '/dashboard/scenarios': typeof AuthenticatedDashboardScenariosRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/sop-library/$id': typeof AuthenticatedSopLibraryIdRoute
  '/sop-library/new': typeof AuthenticatedSopLibraryNewRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/post-auth': typeof PostAuthRoute
  '/register': typeof RegisterRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/growth-roadmap': typeof AuthenticatedGrowthRoadmapRoute
  '/_authenticated/knowledge-base': typeof AuthenticatedKnowledgeBaseRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/sightline': typeof AuthenticatedSightlineRoute
  '/_authenticated/sop-library': typeof AuthenticatedSopLibraryRouteWithChildren
  '/_authenticated/time-calendar': typeof AuthenticatedTimeCalendarRoute
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/_authenticated/dashboard/annual-summary': typeof AuthenticatedDashboardAnnualSummaryRoute
  '/_authenticated/dashboard/bva': typeof AuthenticatedDashboardBvaRoute
  '/_authenticated/dashboard/growth': typeof AuthenticatedDashboardGrowthRoute
  '/_authenticated/dashboard/health': typeof AuthenticatedDashboardHealthRoute
  '/_authenticated/dashboard/knowledge': typeof AuthenticatedDashboardKnowledgeRoute
  '/_authenticated/dashboard/rate': typeof AuthenticatedDashboardRateRoute
  '/_authenticated/dashboard/scenarios': typeof AuthenticatedDashboardScenariosRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/_authenticated/sop-library/$id': typeof AuthenticatedSopLibraryIdRoute
  '/_authenticated/sop-library/new': typeof AuthenticatedSopLibraryNewRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/post-auth'
    | '/register'
    | '/admin'
    | '/billing'
    | '/calendar'
    | '/dashboard'
    | '/growth-roadmap'
    | '/knowledge-base'
    | '/onboarding'
    | '/projects'
    | '/settings'
    | '/setup'
    | '/sightline'
    | '/sop-library'
    | '/time-calendar'
    | '/welcome'
    | '/dashboard/annual-summary'
    | '/dashboard/bva'
    | '/dashboard/growth'
    | '/dashboard/health'
    | '/dashboard/knowledge'
    | '/dashboard/rate'
    | '/dashboard/scenarios'
    | '/projects/$id'
    | '/sop-library/$id'
    | '/sop-library/new'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/post-auth'
    | '/register'
    | '/admin'
    | '/billing'
    | '/calendar'
    | '/dashboard'
    | '/growth-roadmap'
    | '/knowledge-base'
    | '/onboarding'
    | '/projects'
    | '/settings'
    | '/setup'
    | '/sightline'
    | '/sop-library'
    | '/time-calendar'
    | '/welcome'
    | '/dashboard/annual-summary'
    | '/dashboard/bva'
    | '/dashboard/growth'
    | '/dashboard/health'
    | '/dashboard/knowledge'
    | '/dashboard/rate'
    | '/dashboard/scenarios'
    | '/projects/$id'
    | '/sop-library/$id'
    | '/sop-library/new'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invite'
    | '/login'
    | '/post-auth'
    | '/register'
    | '/_authenticated/admin'
    | '/_authenticated/billing'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/growth-roadmap'
    | '/_authenticated/knowledge-base'
    | '/_authenticated/onboarding'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/_authenticated/setup'
    | '/_authenticated/sightline'
    | '/_authenticated/sop-library'
    | '/_authenticated/time-calendar'
    | '/_authenticated/welcome'
    | '/_authenticated/dashboard/annual-summary'
    | '/_authenticated/dashboard/bva'
    | '/_authenticated/dashboard/growth'
    | '/_authenticated/dashboard/health'
    | '/_authenticated/dashboard/knowledge'
    | '/_authenticated/dashboard/rate'
    | '/_authenticated/dashboard/scenarios'
    | '/_authenticated/projects/$id'
    | '/_authenticated/sop-library/$id'
    | '/_authenticated/sop-library/new'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  LoginRoute: typeof LoginRoute
  PostAuthRoute: typeof PostAuthRoute
  RegisterRoute: typeof RegisterRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-auth': {
      id: '/post-auth'
      path: '/post-auth'
      fullPath: '/post-auth'
      preLoaderRoute: typeof PostAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/time-calendar': {
      id: '/_authenticated/time-calendar'
      path: '/time-calendar'
      fullPath: '/time-calendar'
      preLoaderRoute: typeof AuthenticatedTimeCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sop-library': {
      id: '/_authenticated/sop-library'
      path: '/sop-library'
      fullPath: '/sop-library'
      preLoaderRoute: typeof AuthenticatedSopLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sightline': {
      id: '/_authenticated/sightline'
      path: '/sightline'
      fullPath: '/sightline'
      preLoaderRoute: typeof AuthenticatedSightlineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge-base': {
      id: '/_authenticated/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof AuthenticatedKnowledgeBaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/growth-roadmap': {
      id: '/_authenticated/growth-roadmap'
      path: '/growth-roadmap'
      fullPath: '/growth-roadmap'
      preLoaderRoute: typeof AuthenticatedGrowthRoadmapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sop-library/new': {
      id: '/_authenticated/sop-library/new'
      path: '/new'
      fullPath: '/sop-library/new'
      preLoaderRoute: typeof AuthenticatedSopLibraryNewRouteImport
      parentRoute: typeof AuthenticatedSopLibraryRoute
    }
    '/_authenticated/sop-library/$id': {
      id: '/_authenticated/sop-library/$id'
      path: '/$id'
      fullPath: '/sop-library/$id'
      preLoaderRoute: typeof AuthenticatedSopLibraryIdRouteImport
      parentRoute: typeof AuthenticatedSopLibraryRoute
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/dashboard/scenarios': {
      id: '/_authenticated/dashboard/scenarios'
      path: '/scenarios'
      fullPath: '/dashboard/scenarios'
      preLoaderRoute: typeof AuthenticatedDashboardScenariosRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/rate': {
      id: '/_authenticated/dashboard/rate'
      path: '/rate'
      fullPath: '/dashboard/rate'
      preLoaderRoute: typeof AuthenticatedDashboardRateRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/knowledge': {
      id: '/_authenticated/dashboard/knowledge'
      path: '/knowledge'
      fullPath: '/dashboard/knowledge'
      preLoaderRoute: typeof AuthenticatedDashboardKnowledgeRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/health': {
      id: '/_authenticated/dashboard/health'
      path: '/health'
      fullPath: '/dashboard/health'
      preLoaderRoute: typeof AuthenticatedDashboardHealthRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/growth': {
      id: '/_authenticated/dashboard/growth'
      path: '/growth'
      fullPath: '/dashboard/growth'
      preLoaderRoute: typeof AuthenticatedDashboardGrowthRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/bva': {
      id: '/_authenticated/dashboard/bva'
      path: '/bva'
      fullPath: '/dashboard/bva'
      preLoaderRoute: typeof AuthenticatedDashboardBvaRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/annual-summary': {
      id: '/_authenticated/dashboard/annual-summary'
      path: '/annual-summary'
      fullPath: '/dashboard/annual-summary'
      preLoaderRoute: typeof AuthenticatedDashboardAnnualSummaryRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAnnualSummaryRoute: typeof AuthenticatedDashboardAnnualSummaryRoute
  AuthenticatedDashboardBvaRoute: typeof AuthenticatedDashboardBvaRoute
  AuthenticatedDashboardGrowthRoute: typeof AuthenticatedDashboardGrowthRoute
  AuthenticatedDashboardHealthRoute: typeof AuthenticatedDashboardHealthRoute
  AuthenticatedDashboardKnowledgeRoute: typeof AuthenticatedDashboardKnowledgeRoute
  AuthenticatedDashboardRateRoute: typeof AuthenticatedDashboardRateRoute
  AuthenticatedDashboardScenariosRoute: typeof AuthenticatedDashboardScenariosRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAnnualSummaryRoute:
      AuthenticatedDashboardAnnualSummaryRoute,
    AuthenticatedDashboardBvaRoute: AuthenticatedDashboardBvaRoute,
    AuthenticatedDashboardGrowthRoute: AuthenticatedDashboardGrowthRoute,
    AuthenticatedDashboardHealthRoute: AuthenticatedDashboardHealthRoute,
    AuthenticatedDashboardKnowledgeRoute: AuthenticatedDashboardKnowledgeRoute,
    AuthenticatedDashboardRateRoute: AuthenticatedDashboardRateRoute,
    AuthenticatedDashboardScenariosRoute: AuthenticatedDashboardScenariosRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedSopLibraryRouteChildren {
  AuthenticatedSopLibraryIdRoute: typeof AuthenticatedSopLibraryIdRoute
  AuthenticatedSopLibraryNewRoute: typeof AuthenticatedSopLibraryNewRoute
}

const AuthenticatedSopLibraryRouteChildren: AuthenticatedSopLibraryRouteChildren =
  {
    AuthenticatedSopLibraryIdRoute: AuthenticatedSopLibraryIdRoute,
    AuthenticatedSopLibraryNewRoute: AuthenticatedSopLibraryNewRoute,
  }

const AuthenticatedSopLibraryRouteWithChildren =
  AuthenticatedSopLibraryRoute._addFileChildren(
    AuthenticatedSopLibraryRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedGrowthRoadmapRoute: typeof AuthenticatedGrowthRoadmapRoute
  AuthenticatedKnowledgeBaseRoute: typeof AuthenticatedKnowledgeBaseRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedSightlineRoute: typeof AuthenticatedSightlineRoute
  AuthenticatedSopLibraryRoute: typeof AuthenticatedSopLibraryRouteWithChildren
  AuthenticatedTimeCalendarRoute: typeof AuthenticatedTimeCalendarRoute
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedGrowthRoadmapRoute: AuthenticatedGrowthRoadmapRoute,
  AuthenticatedKnowledgeBaseRoute: AuthenticatedKnowledgeBaseRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedSightlineRoute: AuthenticatedSightlineRoute,
  AuthenticatedSopLibraryRoute: AuthenticatedSopLibraryRouteWithChildren,
  AuthenticatedTimeCalendarRoute: AuthenticatedTimeCalendarRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  LoginRoute: LoginRoute,
  PostAuthRoute: PostAuthRoute,
  RegisterRoute: RegisterRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
