/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PostAuthRouteImport } from './routes/post-auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTimeCalendarRouteImport } from './routes/_authenticated/time-calendar'
import { Route as AuthenticatedSopLibraryRouteImport } from './routes/_authenticated/sop-library'
import { Route as AuthenticatedSightlineRouteImport } from './routes/_authenticated/sightline'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRateArchitectureRouteImport } from './routes/_authenticated/rate-architecture'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedKnowledgeBaseRouteImport } from './routes/_authenticated/knowledge-base'
import { Route as AuthenticatedGrowthRoadmapRouteImport } from './routes/_authenticated/growth-roadmap'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRateRouteImport } from './routes/_authenticated/dashboard.rate'
import { Route as AuthenticatedDashboardBvaRouteImport } from './routes/_authenticated/dashboard.bva'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PostAuthRoute = PostAuthRouteImport.update({
  id: '/post-auth',
  path: '/post-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTimeCalendarRoute =
  AuthenticatedTimeCalendarRouteImport.update({
    id: '/time-calendar',
    path: '/time-calendar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSopLibraryRoute = AuthenticatedSopLibraryRouteImport.update({
  id: '/sop-library',
  path: '/sop-library',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSightlineRoute = AuthenticatedSightlineRouteImport.update({
  id: '/sightline',
  path: '/sightline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRateArchitectureRoute =
  AuthenticatedRateArchitectureRouteImport.update({
    id: '/rate-architecture',
    path: '/rate-architecture',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedKnowledgeBaseRoute =
  AuthenticatedKnowledgeBaseRouteImport.update({
    id: '/knowledge-base',
    path: '/knowledge-base',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGrowthRoadmapRoute =
  AuthenticatedGrowthRoadmapRouteImport.update({
    id: '/growth-roadmap',
    path: '/growth-roadmap',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRateRoute =
  AuthenticatedDashboardRateRouteImport.update({
    id: '/rate',
    path: '/rate',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardBvaRoute =
  AuthenticatedDashboardBvaRouteImport.update({
    id: '/bva',
    path: '/bva',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/post-auth': typeof PostAuthRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/growth-roadmap': typeof AuthenticatedGrowthRoadmapRoute
  '/knowledge-base': typeof AuthenticatedKnowledgeBaseRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/rate-architecture': typeof AuthenticatedRateArchitectureRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sightline': typeof AuthenticatedSightlineRoute
  '/sop-library': typeof AuthenticatedSopLibraryRoute
  '/time-calendar': typeof AuthenticatedTimeCalendarRoute
  '/dashboard/bva': typeof AuthenticatedDashboardBvaRoute
  '/dashboard/rate': typeof AuthenticatedDashboardRateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/post-auth': typeof PostAuthRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/growth-roadmap': typeof AuthenticatedGrowthRoadmapRoute
  '/knowledge-base': typeof AuthenticatedKnowledgeBaseRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/rate-architecture': typeof AuthenticatedRateArchitectureRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sightline': typeof AuthenticatedSightlineRoute
  '/sop-library': typeof AuthenticatedSopLibraryRoute
  '/time-calendar': typeof AuthenticatedTimeCalendarRoute
  '/dashboard/bva': typeof AuthenticatedDashboardBvaRoute
  '/dashboard/rate': typeof AuthenticatedDashboardRateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/post-auth': typeof PostAuthRoute
  '/register': typeof RegisterRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/growth-roadmap': typeof AuthenticatedGrowthRoadmapRoute
  '/_authenticated/knowledge-base': typeof AuthenticatedKnowledgeBaseRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/rate-architecture': typeof AuthenticatedRateArchitectureRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sightline': typeof AuthenticatedSightlineRoute
  '/_authenticated/sop-library': typeof AuthenticatedSopLibraryRoute
  '/_authenticated/time-calendar': typeof AuthenticatedTimeCalendarRoute
  '/_authenticated/dashboard/bva': typeof AuthenticatedDashboardBvaRoute
  '/_authenticated/dashboard/rate': typeof AuthenticatedDashboardRateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/post-auth'
    | '/register'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/growth-roadmap'
    | '/knowledge-base'
    | '/onboarding'
    | '/rate-architecture'
    | '/settings'
    | '/sightline'
    | '/sop-library'
    | '/time-calendar'
    | '/dashboard/bva'
    | '/dashboard/rate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/post-auth'
    | '/register'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/growth-roadmap'
    | '/knowledge-base'
    | '/onboarding'
    | '/rate-architecture'
    | '/settings'
    | '/sightline'
    | '/sop-library'
    | '/time-calendar'
    | '/dashboard/bva'
    | '/dashboard/rate'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/post-auth'
    | '/register'
    | '/_authenticated/admin'
    | '/_authenticated/billing'
    | '/_authenticated/dashboard'
    | '/_authenticated/growth-roadmap'
    | '/_authenticated/knowledge-base'
    | '/_authenticated/onboarding'
    | '/_authenticated/rate-architecture'
    | '/_authenticated/settings'
    | '/_authenticated/sightline'
    | '/_authenticated/sop-library'
    | '/_authenticated/time-calendar'
    | '/_authenticated/dashboard/bva'
    | '/_authenticated/dashboard/rate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PostAuthRoute: typeof PostAuthRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-auth': {
      id: '/post-auth'
      path: '/post-auth'
      fullPath: '/post-auth'
      preLoaderRoute: typeof PostAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/time-calendar': {
      id: '/_authenticated/time-calendar'
      path: '/time-calendar'
      fullPath: '/time-calendar'
      preLoaderRoute: typeof AuthenticatedTimeCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sop-library': {
      id: '/_authenticated/sop-library'
      path: '/sop-library'
      fullPath: '/sop-library'
      preLoaderRoute: typeof AuthenticatedSopLibraryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sightline': {
      id: '/_authenticated/sightline'
      path: '/sightline'
      fullPath: '/sightline'
      preLoaderRoute: typeof AuthenticatedSightlineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rate-architecture': {
      id: '/_authenticated/rate-architecture'
      path: '/rate-architecture'
      fullPath: '/rate-architecture'
      preLoaderRoute: typeof AuthenticatedRateArchitectureRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/knowledge-base': {
      id: '/_authenticated/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof AuthenticatedKnowledgeBaseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/growth-roadmap': {
      id: '/_authenticated/growth-roadmap'
      path: '/growth-roadmap'
      fullPath: '/growth-roadmap'
      preLoaderRoute: typeof AuthenticatedGrowthRoadmapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/rate': {
      id: '/_authenticated/dashboard/rate'
      path: '/rate'
      fullPath: '/dashboard/rate'
      preLoaderRoute: typeof AuthenticatedDashboardRateRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/bva': {
      id: '/_authenticated/dashboard/bva'
      path: '/bva'
      fullPath: '/dashboard/bva'
      preLoaderRoute: typeof AuthenticatedDashboardBvaRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardBvaRoute: typeof AuthenticatedDashboardBvaRoute
  AuthenticatedDashboardRateRoute: typeof AuthenticatedDashboardRateRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardBvaRoute: AuthenticatedDashboardBvaRoute,
    AuthenticatedDashboardRateRoute: AuthenticatedDashboardRateRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedGrowthRoadmapRoute: typeof AuthenticatedGrowthRoadmapRoute
  AuthenticatedKnowledgeBaseRoute: typeof AuthenticatedKnowledgeBaseRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRateArchitectureRoute: typeof AuthenticatedRateArchitectureRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSightlineRoute: typeof AuthenticatedSightlineRoute
  AuthenticatedSopLibraryRoute: typeof AuthenticatedSopLibraryRoute
  AuthenticatedTimeCalendarRoute: typeof AuthenticatedTimeCalendarRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedGrowthRoadmapRoute: AuthenticatedGrowthRoadmapRoute,
  AuthenticatedKnowledgeBaseRoute: AuthenticatedKnowledgeBaseRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRateArchitectureRoute: AuthenticatedRateArchitectureRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSightlineRoute: AuthenticatedSightlineRoute,
  AuthenticatedSopLibraryRoute: AuthenticatedSopLibraryRoute,
  AuthenticatedTimeCalendarRoute: AuthenticatedTimeCalendarRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PostAuthRoute: PostAuthRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
